#!/bin/sh
# https://github.com/tianj-zh/qtmultimedia.git
#./sync-fork.sh qtmultimedia
# https://github.com/tianj-zh/qtnetworkauth.git
#./sync-fork.sh qtnetworkauth
# https://github.com/tianj-zh/qtmacextras.git
#./sync-fork.sh qtmacextras
# https://github.com/tianj-zh/qt3d.git
#./sync-fork.sh qt3d
# https://github.com/tianj-zh/qtlocation-mapboxgl.git
./sync-fork.sh qtlocation-mapboxgl
# https://github.com/tianj-zh/qtlocation.git
#./sync-fork.sh qtlocation
# https://github.com/tianj-zh/qtimageformats.git
#./sync-fork.sh qtimageformats
# https://github.com/tianj-zh/qtgraphicaleffects.git
#./sync-fork.sh qtgraphicaleffects
# https://github.com/tianj-zh/qtgamepad.git
#./sync-fork.sh qtgamepad
# https://github.com/tianj-zh/qtdoc.git
#./sync-fork.sh qtdoc
# https://github.com/tianj-zh/qtdeclarative.git
#./sync-fork.sh qtdeclarative
# https://github.com/tianj-zh/qtdatavis3d.git
#./sync-fork.sh qtdatavis3d
# https://github.com/tianj-zh/qtconnectivity.git
#./sync-fork.sh qtconnectivity
# https://github.com/tianj-zh/qtcharts.git
#./sync-fork.sh qtcharts
# https://github.com/tianj-zh/qtcanvas3d.git
#./sync-fork.sh qtcanvas3d
# https://github.com/tianj-zh/qtbase.git
#./sync-fork.sh qtbase
# https://github.com/tianj-zh/qtandroidextras.git
#./sync-fork.sh qtandroidextras
# https://github.com/tianj-zh/qtactiveqt.git
#./sync-fork.sh qtactiveqt
# https://github.com/tianj-zh/qt5.git
./sync-fork.sh qt5
# https://github.com/tianj-zh/qtwebengine.git
#./sync-fork.sh qtwebengine
# https://github.com/tianj-zh/qtwebengine-chromium.git
#./sync-fork.sh qtwebengine-chromium
# https://github.com/tianj-zh/qtquickcontrols.git
#./sync-fork.sh qtquickcontrols
# https://github.com/tianj-zh/qtremoteobjects.git
#./sync-fork.sh qtremoteobjects
# https://github.com/tianj-zh/qttranslations.git
#./sync-fork.sh qttranslations
# https://github.com/tianj-zh/qttools.git
#./sync-fork.sh qttools
# https://github.com/tianj-zh/qtwebglplugin.git
#./sync-fork.sh qtwebglplugin
# https://github.com/tianj-zh/qtspeech.git
#./sync-fork.sh qtspeech
# https://github.com/tianj-zh/qtscxml.git
#./sync-fork.sh qtscxml
# https://github.com/tianj-zh/qtvirtualkeyboard.git
#./sync-fork.sh qtvirtualkeyboard
# https://github.com/tianj-zh/qtpurchasing.git
#./sync-fork.sh qtpurchasing
# https://github.com/tianj-zh/qtquickcontrols2.git
#./sync-fork.sh qtquickcontrols2
# https://github.com/tianj-zh/qtwebview.git
#./sync-fork.sh qtwebview
# https://github.com/tianj-zh/qtwebchannel.git
#./sync-fork.sh qtwebchannel
# https://github.com/tianj-zh/qtwebsockets.git
#./sync-fork.sh qtwebsockets
# https://github.com/tianj-zh/qtwinextras.git
#./sync-fork.sh qtwinextras
# https://github.com/tianj-zh/qtx11extras.git
#./sync-fork.sh qtx11extras
# https://github.com/tianj-zh/qtserialport.git
#./sync-fork.sh qtserialport
# https://github.com/tianj-zh/qtserialbus.git
#./sync-fork.sh qtserialbus
# https://github.com/tianj-zh/qtwayland.git
#./sync-fork.sh qtwayland
# https://github.com/tianj-zh/qtsensors.git
#./sync-fork.sh qtsensors
# https://github.com/tianj-zh/qtxmlpatterns.git
#./sync-fork.sh qtxmlpatterns
# https://github.com/tianj-zh/qtscript.git
#./sync-fork.sh qtscript
# https://github.com/tianj-zh/qtsvg.git
#./sync-fork.sh qtsvg
# https://github.com/tianj-zh/qtpim.git
#./sync-fork.sh qtpim
# https://github.com/tianj-zh/qtqa.git
#./sync-fork.sh qtqa
# https://github.com/tianj-zh/qtrepotools.git
#./sync-fork.sh qtrepotools
# https://github.com/tianj-zh/qtfeedback.git
#./sync-fork.sh qtfeedback
# https://github.com/tianj-zh/qtdeclarative-testsuites.git
#./sync-fork.sh qtdeclarative-testsuites
# https://github.com/tianj-zh/qtsystems.git
#./sync-fork.sh qtsystems
# https://github.com/tianj-zh/qtwebkit.git
#./sync-fork.sh qtwebkit
# https://github.com/tianj-zh/qtquick1.git
#./sync-fork.sh qtquick1
# https://github.com/tianj-zh/qtenginio.git
#./sync-fork.sh qtenginio
# https://github.com/tianj-zh/qtwebkit-examples.git
#./sync-fork.sh qtwebkit-examples
# https://github.com/tianj-zh/qtdocgallery.git
#./sync-fork.sh qtdocgallery
# https://github.com/tianj-zh/qtxmlpatterns-testsuites.git
#./sync-fork.sh qtxmlpatterns-testsuites